### ISSUE TITLE
'this' in clientManager is not available to server extensions

### ISSUE THREAD

**Issue by rhclayto** [beejeebus/drupal-nodejs#22]
Hi,

I have a server extension (modified from the one in Nodejs Chat). When I try to use methods on clientManager.backend (sendMessageToBackend in particular), no message is sent to the backend. When I put `console.log('this: ', this);` into `Backend.prototype.sendMessageToBackend`, I get `this: undefined`. So none of the 'this' methods/properties in sendMessageToBackend  are working, such as `this.settings.serviceKey`, `this.getAuthHeader()`, etc.

Below is my extension code:

```javascript
/**
 * @file nodejs_chat.module.js
 *
 * Node JS Chat Server extension.
 */
 
'use strict';

var chatExtension = {};

chatExtension.setup = function (clientManager) {
  var publishMessageToChannel = clientManager.publishMessageToChannel;
  var addClientToChannel = clientManager.addClientToChannel;
	var backend = clientManager.backend;
  var sendMessageToBackend = clientManager.backend.sendMessageToBackend;
  var channels = clientManager.channels;

  process.on('client-to-channel-message', function (sessionId, message) {
    // Check message type. Prevents the extension from forwarding any message
    // that is not from the nodejs_chat module.
    if (message.type == 'nodejs_chat') {
      console.log('Node JS Chat extension received a "client-message" event. Action: ' + message.action);
      switch (message.action) {
        // When chat is initialised, user needs to be added to the chat Channel.
        case 'chat_init':
          // Validate against the back-end, that the user can be added indeed to
          // the requested channel (if he's not already added).
          if (!channels[message.channel].sessionIds[sessionId]) {				
            sendMessageToBackend(
              {
                messageType: 'nodejs_chat_' + message.action,
                channel: message.channel,
                data: message.data
              }, function (error, response, body) {
                var responseData = JSON.parse(body);
				
                if (responseData.data == true) {
                  addClientToChannel(sessionId, message.channel);

                  // When entering a chat channel, the client might have sent a message
                  // so that users know about this.
                  publishMessageToChannel(message);
                }
              });
          }
          break;
        // Usual message transmission.
        case 'chat_message':
          publishMessageToChannel(message);
          break;
      }
    }
  });

};

module.exports = chatExtension;
```

In the logs, multiple messages such as: 

```
Missing error handler on `socket`.
TypeError: Cannot read property 'settings' of undefined
    at Backend.sendMessageToBackend (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/drupal-node.js/lib/backend.js:72:21)
    at process.<anonymous> (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/drupal-node.js/extensions/nodejs_chat.module.js:34:13)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at ClientManager.processMessage (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/drupal-node.js/lib/client-manager.js:158:17)
    at Socket.<anonymous> (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/drupal-node.js/lib/client-manager.js:46:23)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/var/www/hosting/tellingua/com/drupal_nodejs/node_modules/socket.io/lib/socket.js:295:12)
```

Any ideas?

**Comment by glekli** [comment]
Methods on objects need to be called in their context. When you reference the method directly with a variable, and call that, it loses the context, and `this` will not be the same as if you called the method via the object.
So, instead of this:
```javascript
var sendMessageToBackend = clientManager.backend.sendMessageToBackend;
sendMessageToBackend();
```
try using it like this:
```javascript
var backend = clientManager.backend;
backend.sendMessageToBackend();
```

**Comment by rhclayto** [comment]
Hi glekli,

Indeed that was the problem. I was reading up on the 'this' subtleties (insanities?) in Javascript, but the descriptions of the problem i found through Google were not nearly as clear & concise as yours. Oh Javascript. Many thanks for the pointer. and thanks for your work on this module.

H.
